### ISSUE TITLE
Drive around in a tank

### ISSUE THREAD

**Issue by chase-moskal** [monarch-games/engine#25]
## director entity
 - [x] spawn player tank at origin with R key ("r" for "respawn", maybe)

## tank entity
 - [x] third person camera rig is controlled via the mouse
 - [ ] rename "agent" entity to "tank" entity
    - originally, I thought about creating some kind of generic base-class for "playable" characters like tanks and such
    - now, I think I'm more in favor of just having the tank entity, where it utilizes handy functions similar to those found in a common place like camtools
 - [ ] can drive around with WASD — physics
    - integrate ammojs (for proper convex-hull rigid bodies)
    - otherwise use raycasting techniques (to save performance)
    - movement is relative to the camera
        - W/S to go forward/back
        - A/D to strafe left/right
 - [ ] aiming reticle
 - [ ] tank has a turret which follows your reticle

**Comment by ChaseMoskal** [comment]
might reconsider and only put nanoshooter stuff in nanoshooter :/
